-- ┌──────────────────────────────────────────────────────────────────────────┐
-- │ 001 · Datos académicos — universidad › plan › materias/correlativas/     │
-- │       títulos.  (Sprint 1, paso 1 — ago 2026)                            │
-- └──────────────────────────────────────────────────────────────────────────┘
--
-- Cómo correrlo: Supabase → SQL Editor → pegar TODO → Run. Es idempotente
-- (`if not exists` / `or replace`): volver a correrlo no rompe nada.
--
-- Mapea 1:1 a `src/data/model.ts`, que ya estaba normalizado pensando en esto.
-- Después de esto va `supabase/seed-planes.sql` (lo genera
-- `node scripts/gen-seed-planes.mjs` desde los 4 planes del repo).
--
-- ⚠️ Este archivo NO toca la tabla `progreso` (el avance del alumno, 1 fila JSON
--    por usuario con RLS `user_id = auth.uid()`). Sigue igual de cerrada que
--    siempre: ningún rol nuevo la alcanza, y el panel agregado del futuro NO va a
--    leerla — va a leer vistas agregadas.
--
-- ⚠️ Permisos: acá se habilita RLS con políticas de SOLO LECTURA pública (planes
--    publicados). NO se crea ninguna política de escritura: hoy solo se puede
--    escribir desde el SQL Editor / service_role. Los roles (superadmin ·
--    admin_uni con límite por universidad · estudiante) llegan en 002.

-- ── Universidades ─────────────────────────────────────────────────────────
create table if not exists public.universidad (
  id          text primary key,                    -- slug estable, ej. 'uade'
  nombre      text not null,
  activa      boolean not null default true,
  creado_at   timestamptz not null default now()
);

-- ── Planes ────────────────────────────────────────────────────────────────
create table if not exists public.plan (
  id               text primary key,               -- slug estable, ej. 'uade-ing-informatica'
  universidad_id   text not null references public.universidad(id) on delete restrict,
  codigo           text not null,                  -- código del plan en la facu, ej. '1621'
  anio             int  not null,                  -- año de vigencia del plan
  carrera          text not null,
  estado           text not null default 'borrador'
                     check (estado in ('borrador', 'publicado')),
  version          int  not null default 1,
  publicado_at     timestamptz,
  actualizado_at   timestamptz not null default now(),
  actualizado_por  uuid references auth.users(id) on delete set null,
  orden            int  not null default 0,        -- orden en el selector de carrera
  unique (universidad_id, codigo, anio)
);

create index if not exists plan_universidad_idx on public.plan (universidad_id);
create index if not exists plan_publicados_idx  on public.plan (estado) where estado = 'publicado';

-- ── Materias ──────────────────────────────────────────────────────────────
-- La PK compuesta (plan_id, cod) es la que permite que `correlativa` referencie
-- materias POR FK: la base misma impide una correlativa que apunte a un código
-- inexistente o a otro plan. Defensa en profundidad con validarPlan().
create table if not exists public.materia (
  plan_id    text not null references public.plan(id) on delete cascade,
  cod        text not null,
  nom        text not null,
  anio       int  not null check (anio >= 1),
  cuatri     int  not null check (cuatri in (1, 2)),
  opt        boolean not null default false,       -- optativa: slot renombrable por el alumno
  especial   boolean not null default false,       -- se habilita por requisito especial, no por correlativa
  orden      int  not null default 0,              -- orden dentro del cuatrimestre (preserva el orden del plan oficial)
  primary key (plan_id, cod)
);

create index if not exists materia_orden_idx on public.materia (plan_id, anio, cuatri, orden);

-- ── Correlativas ──────────────────────────────────────────────────────────
create table if not exists public.correlativa (
  plan_id    text not null references public.plan(id) on delete cascade,
  cod        text not null,                        -- la materia
  requiere   text not null,                        -- la que necesita antes
  orden      int  not null default 0,
  primary key (plan_id, cod, requiere),
  check (cod <> requiere),
  foreign key (plan_id, cod)      references public.materia(plan_id, cod) on delete cascade,
  foreign key (plan_id, requiere) references public.materia(plan_id, cod) on delete cascade
);

-- ── Títulos ───────────────────────────────────────────────────────────────
create table if not exists public.titulo (
  id            bigint generated by default as identity primary key,
  plan_id       text not null references public.plan(id) on delete cascade,
  nombre        text not null,
  hasta_anio    int  not null check (hasta_anio >= 1),
  hasta_cuatri  int  check (hasta_cuatri in (1, 2)),  -- null = el año completo
  orden         int  not null default 0
);

create index if not exists titulo_plan_idx on public.titulo (plan_id, orden);

-- ── "Última edición" real ─────────────────────────────────────────────────
-- Tocar una materia/correlativa/título actualiza el plan padre, así el editor puede
-- mostrar cuándo se editó de verdad y el caché del cliente sabe que algo cambió.
-- `security definer` a propósito: es contabilidad interna, no depende de que quien
-- edita tenga permiso de UPDATE sobre la fila del plan.
create or replace function public.tocar_plan()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.plan
     set actualizado_at = now()
   where id = coalesce(new.plan_id, old.plan_id);
  return coalesce(new, old);
end;
$$;

create or replace function public.tocar_plan_propio()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.actualizado_at = now();
  return new;
end;
$$;

drop trigger if exists plan_tocado on public.plan;
create trigger plan_tocado before update on public.plan
  for each row execute function public.tocar_plan_propio();

drop trigger if exists materia_toca_plan on public.materia;
create trigger materia_toca_plan after insert or update or delete on public.materia
  for each row execute function public.tocar_plan();

drop trigger if exists correlativa_toca_plan on public.correlativa;
create trigger correlativa_toca_plan after insert or update or delete on public.correlativa
  for each row execute function public.tocar_plan();

drop trigger if exists titulo_toca_plan on public.titulo;
create trigger titulo_toca_plan after insert or update or delete on public.titulo
  for each row execute function public.tocar_plan();

-- ── RLS: lectura pública de lo PUBLICADO, cero escritura ──────────────────
alter table public.universidad enable row level security;
alter table public.plan        enable row level security;
alter table public.materia     enable row level security;
alter table public.correlativa enable row level security;
alter table public.titulo      enable row level security;

drop policy if exists universidad_lectura on public.universidad;
create policy universidad_lectura on public.universidad
  for select to anon, authenticated using (activa);

drop policy if exists plan_lectura on public.plan;
create policy plan_lectura on public.plan
  for select to anon, authenticated using (estado = 'publicado');

-- Las hijas se leen solo si su plan es legible (la subconsulta pasa por la policy de plan).
drop policy if exists materia_lectura on public.materia;
create policy materia_lectura on public.materia
  for select to anon, authenticated
  using (exists (select 1 from public.plan p where p.id = plan_id));

drop policy if exists correlativa_lectura on public.correlativa;
create policy correlativa_lectura on public.correlativa
  for select to anon, authenticated
  using (exists (select 1 from public.plan p where p.id = plan_id));

drop policy if exists titulo_lectura on public.titulo;
create policy titulo_lectura on public.titulo
  for select to anon, authenticated
  using (exists (select 1 from public.plan p where p.id = plan_id));

-- ── La vista que consume la app ───────────────────────────────────────────
-- Devuelve un plan por fila, con la forma EXACTA de `PlanDef` (por eso el
-- strip_nulls: `opt`/`especial` viajan solo cuando son true, igual que en los
-- módulos TS del bundle). Una sola consulta, sin armado en el cliente.
--
-- `security_invoker = true`: la vista respeta el RLS de quien pregunta, así que
-- desde el navegador solo salen los planes publicados.
create or replace view public.plan_publicado
with (security_invoker = true) as
select
  p.id,
  p.universidad_id                                   as universidad,
  p.codigo,
  p.anio,
  p.carrera,
  p.version,
  p.actualizado_at,
  p.orden,
  coalesce((
    select jsonb_agg(jsonb_strip_nulls(jsonb_build_object(
             'cod', m.cod, 'nom', m.nom, 'anio', m.anio, 'cuatri', m.cuatri,
             'opt',      case when m.opt      then true end,
             'especial', case when m.especial then true end))
                     order by m.anio, m.cuatri, m.orden, m.cod)
      from public.materia m where m.plan_id = p.id), '[]'::jsonb)      as materias,
  coalesce((
    select jsonb_agg(jsonb_build_object('cod', c.cod, 'requiere', c.requiere)
                     order by c.orden, c.cod, c.requiere)
      from public.correlativa c where c.plan_id = p.id), '[]'::jsonb)  as correlativas,
  coalesce((
    select jsonb_agg(jsonb_strip_nulls(jsonb_build_object(
             'nombre', t.nombre, 'hastaAnio', t.hasta_anio, 'hastaCuatri', t.hasta_cuatri))
                     order by t.orden, t.id)
      from public.titulo t where t.plan_id = p.id), '[]'::jsonb)       as titulos
from public.plan p
where p.estado = 'publicado';

grant select on public.plan_publicado to anon, authenticated;

-- ── Verificación rápida (después del seed debería dar 4 planes) ───────────
-- select id, carrera, jsonb_array_length(materias) as materias,
--        jsonb_array_length(correlativas) as correlativas
--   from public.plan_publicado order by carrera;
