-- ┌──────────────────────────────────────────────────────────────────────────┐
-- │ 002 · Perfiles y permisos — superadmin · admin de universidad ·          │
-- │       estudiante.  (Sprint 1, paso 2 — ago 2026)                         │
-- └──────────────────────────────────────────────────────────────────────────┘
--
-- Cómo correrlo: Supabase → SQL Editor → pegar TODO → Run. Idempotente.
-- Requiere 001-datos-academicos.sql.
-- Después conviene correr 003-verificar-permisos.sql, que prueba cada regla
-- simulando usuarios y termina en ROLLBACK (no deja nada).
--
-- QUÉ HABILITA: hasta ahora las tablas académicas eran de solo lectura vía API
-- (se escribían nada más que desde este editor). Acá aparecen las políticas de
-- escritura, atadas a tres roles y con LÍMITE DE PLANES por universidad.
--
-- DECISIÓN CLAVE (ADR-11, punto 5): los permisos viven en la BASE, no en el token.
-- Se consultan con funciones `security definer`, no con custom claims del JWT:
-- un claim queda cacheado en el token hasta que se refresca, así que revocarle el
-- permiso a alguien no tendría efecto inmediato. Con funciones, revocar es un UPDATE.
--
-- LO QUE ESTE ARCHIVO NO HACE (a propósito):
--   · El flujo borrador → publicación con versiones. El modelo de versionado se
--     define junto con el editor (paso 3): meter media máquina de estados ahora
--     obligaría a migrarla después. Hoy un admin puede editar su plan publicado.
--   · Validar el plan al publicar: las reglas son las de `validarPlan()` (TypeScript),
--     las hace cumplir el editor, y el arranque de la app descarta cualquier plan roto
--     que llegue igual. La base sostiene aparte lo estructural (claves y FKs).
--   · Tocar `progreso`. Sigue con RLS `user_id = auth.uid()`: NINGÚN rol de acá la
--     alcanza. El chequeo está en 003.

-- ── Perfil: un rol por usuario ────────────────────────────────────────────
create table if not exists public.perfil (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  rol        text not null default 'estudiante'
               check (rol in ('superadmin', 'admin_uni', 'estudiante')),
  creado_at  timestamptz not null default now()
);

-- Toda cuenta nueva arranca como estudiante. La fila no es obligatoria (si falta,
-- las funciones de abajo asumen 'estudiante'), pero tenerla hace visible el padrón.
create or replace function public.perfil_al_registrarse()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.perfil (user_id) values (new.id) on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists perfil_nuevo_usuario on auth.users;
create trigger perfil_nuevo_usuario after insert on auth.users
  for each row execute function public.perfil_al_registrarse();

-- Las cuentas que ya existen (las ~47 de agosto) también entran al padrón.
insert into public.perfil (user_id)
select id from auth.users on conflict (user_id) do nothing;

-- ── Admin de universidad: alcance y límite ────────────────────────────────
-- Una fila por (persona, universidad). El superadmin decide qué puede hacer y
-- CUÁNTOS planes puede tener esa universidad. Sin fila, no puede tocar nada.
create table if not exists public.admin_uni (
  user_id         uuid not null references auth.users(id) on delete cascade,
  universidad_id  text not null references public.universidad(id) on delete cascade,
  crear           boolean not null default false,
  editar          boolean not null default true,
  eliminar        boolean not null default false,
  limite_planes   int  not null default 5 check (limite_planes >= 0),
  otorgado_por    uuid references auth.users(id) on delete set null,
  otorgado_at     timestamptz not null default now(),
  primary key (user_id, universidad_id)
);

create index if not exists admin_uni_universidad_idx on public.admin_uni (universidad_id);

-- ── Auditoría: quién tocó qué y cuándo ────────────────────────────────────
create table if not exists public.auditoria (
  id          bigint generated by default as identity primary key,
  user_id     uuid references auth.users(id) on delete set null,
  tabla       text not null,
  accion      text not null check (accion in ('INSERT', 'UPDATE', 'DELETE')),
  plan_id     text,
  dato        jsonb,
  at          timestamptz not null default now()
);

create index if not exists auditoria_plan_idx on public.auditoria (plan_id, at desc);

-- ── Las funciones que deciden ─────────────────────────────────────────────
-- Todas `stable security definer` con search_path vacío: leen las tablas de
-- permisos sin depender de las políticas de quien pregunta (si no, para saber si
-- puede leer necesitaría poder leer).

create or replace function public.mi_rol()
returns text language sql stable security definer set search_path = '' as $$
  select coalesce((select rol from public.perfil where user_id = auth.uid()), 'estudiante');
$$;

create or replace function public.es_superadmin()
returns boolean language sql stable security definer set search_path = '' as $$
  select public.mi_rol() = 'superadmin';
$$;

/**
 * ¿Tiene el permiso `accion` ('crear' | 'editar' | 'eliminar') sobre esa universidad?
 * El superadmin puede en todas. Un admin, SOLO en las suyas — pasarle a mano el id
 * de otra universidad no alcanza, porque la fila de admin_uni no existe.
 */
create or replace function public.permiso_uni(uni text, accion text)
returns boolean language sql stable security definer set search_path = '' as $$
  select public.es_superadmin() or exists (
    select 1 from public.admin_uni a
     where a.user_id = auth.uid()
       and a.universidad_id = uni
       and case accion
             when 'crear'    then a.crear
             when 'editar'   then a.editar
             when 'eliminar' then a.eliminar
             else false
           end
  );
$$;

/** Cuántos planes tiene una universidad (todos, no solo los que el que pregunta ve). */
create or replace function public.planes_de(uni text)
returns int language sql stable security definer set search_path = '' as $$
  select count(*)::int from public.plan where universidad_id = uni;
$$;

/** ¿Puede crear otro plan sin pasarse del límite de SU universidad? */
create or replace function public.limite_ok(uni text)
returns boolean language sql stable security definer set search_path = '' as $$
  select public.es_superadmin() or exists (
    select 1 from public.admin_uni a
     where a.user_id = auth.uid()
       and a.universidad_id = uni
       and public.planes_de(uni) < a.limite_planes
  );
$$;

/** ¿Puede editar el contenido (materias/correlativas/títulos) de ese plan? */
create or replace function public.puede_editar_plan(p text)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.plan pl
     where pl.id = p and public.permiso_uni(pl.universidad_id, 'editar')
  );
$$;

-- ── RLS de las tablas de permisos ─────────────────────────────────────────
alter table public.perfil    enable row level security;
alter table public.admin_uni enable row level security;
alter table public.auditoria enable row level security;

-- Cada uno ve su propio perfil; el superadmin ve el padrón entero.
drop policy if exists perfil_lectura on public.perfil;
create policy perfil_lectura on public.perfil
  for select to authenticated using (user_id = auth.uid() or public.es_superadmin());

-- El rol NO se auto-asigna: solo el superadmin reparte.
drop policy if exists perfil_escritura on public.perfil;
create policy perfil_escritura on public.perfil
  for all to authenticated using (public.es_superadmin()) with check (public.es_superadmin());

-- Un admin ve sus propias habilitaciones (para saber qué puede hacer la UI).
drop policy if exists admin_uni_lectura on public.admin_uni;
create policy admin_uni_lectura on public.admin_uni
  for select to authenticated using (user_id = auth.uid() or public.es_superadmin());

drop policy if exists admin_uni_escritura on public.admin_uni;
create policy admin_uni_escritura on public.admin_uni
  for all to authenticated using (public.es_superadmin()) with check (public.es_superadmin());

-- La auditoría se lee, no se escribe (la escriben los triggers, que son definer).
drop policy if exists auditoria_lectura on public.auditoria;
create policy auditoria_lectura on public.auditoria
  for select to authenticated using (
    public.es_superadmin() or exists (
      select 1 from public.plan pl
       where pl.id = auditoria.plan_id and public.permiso_uni(pl.universidad_id, 'editar')
    )
  );

-- ── Escritura de los datos académicos ─────────────────────────────────────
-- El admin ve TAMBIÉN los planes de su universidad que no estén publicados (si no,
-- no podría trabajar sobre uno recién creado). Es una política aparte: se suma por OR
-- a la de 001, que sigue dejando ver lo publicado a cualquiera.
drop policy if exists plan_lectura_admin on public.plan;
create policy plan_lectura_admin on public.plan
  for select to authenticated using (public.permiso_uni(universidad_id, 'editar'));

drop policy if exists plan_crear on public.plan;
create policy plan_crear on public.plan
  for insert to authenticated
  with check (public.permiso_uni(universidad_id, 'crear') and public.limite_ok(universidad_id));

-- `using` mira la fila como está; `with check`, como queda. Los dos exigen permiso en
-- la universidad → un admin no puede MUDAR su plan a otra universidad ni robarse uno.
drop policy if exists plan_editar on public.plan;
create policy plan_editar on public.plan
  for update to authenticated
  using (public.permiso_uni(universidad_id, 'editar'))
  with check (public.permiso_uni(universidad_id, 'editar'));

drop policy if exists plan_eliminar on public.plan;
create policy plan_eliminar on public.plan
  for delete to authenticated using (public.permiso_uni(universidad_id, 'eliminar'));

-- Las hijas siguen el permiso de edición de SU plan. `for all` cubre insert, update
-- y delete; el select ya lo resuelven las políticas de 001 (que pasan por plan).
drop policy if exists materia_escritura on public.materia;
create policy materia_escritura on public.materia
  for all to authenticated
  using (public.puede_editar_plan(plan_id)) with check (public.puede_editar_plan(plan_id));

drop policy if exists correlativa_escritura on public.correlativa;
create policy correlativa_escritura on public.correlativa
  for all to authenticated
  using (public.puede_editar_plan(plan_id)) with check (public.puede_editar_plan(plan_id));

drop policy if exists titulo_escritura on public.titulo;
create policy titulo_escritura on public.titulo
  for all to authenticated
  using (public.puede_editar_plan(plan_id)) with check (public.puede_editar_plan(plan_id));

-- Las universidades las crea el superadmin (un admin no se inventa la propia).
drop policy if exists universidad_escritura on public.universidad;
create policy universidad_escritura on public.universidad
  for all to authenticated using (public.es_superadmin()) with check (public.es_superadmin());

-- ── Los triggers de auditoría ─────────────────────────────────────────────
create or replace function public.auditar()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_plan text;
  v_dato jsonb;
begin
  if tg_table_name = 'plan' then
    v_plan := coalesce(new.id, old.id);
  else
    v_plan := coalesce(new.plan_id, old.plan_id);
  end if;
  v_dato := case tg_op
              when 'DELETE' then to_jsonb(old)
              else to_jsonb(new)
            end;
  insert into public.auditoria (user_id, tabla, accion, plan_id, dato)
  values (auth.uid(), tg_table_name, tg_op, v_plan, v_dato - 'plan_id');
  return coalesce(new, old);
end;
$$;

drop trigger if exists plan_auditado on public.plan;
create trigger plan_auditado after insert or update or delete on public.plan
  for each row execute function public.auditar();

drop trigger if exists materia_auditada on public.materia;
create trigger materia_auditada after insert or update or delete on public.materia
  for each row execute function public.auditar();

drop trigger if exists correlativa_auditada on public.correlativa;
create trigger correlativa_auditada after insert or update or delete on public.correlativa
  for each row execute function public.auditar();

drop trigger if exists titulo_auditado on public.titulo;
create trigger titulo_auditado after insert or update or delete on public.titulo
  for each row execute function public.auditar();

-- ── Cómo se reparte un permiso (lo hace el superadmin) ────────────────────
-- 1) Convertirte en superadmin (una sola vez, con tu mail):
--      update public.perfil set rol = 'superadmin'
--       where user_id = (select id from auth.users where email = 'TU-MAIL@gmail.com');
--
-- 2) Habilitar a alguien como admin de una universidad, con su límite:
--      insert into public.admin_uni (user_id, universidad_id, crear, editar, eliminar,
--                                    limite_planes, otorgado_por)
--      select u.id, 'uade', true, true, false, 6, auth.uid()
--        from auth.users u where u.email = 'PERSONA@uade.edu.ar'
--      on conflict (user_id, universidad_id) do update
--        set crear = excluded.crear, editar = excluded.editar,
--            eliminar = excluded.eliminar, limite_planes = excluded.limite_planes;
--
-- 3) Revocar (efecto inmediato, sin esperar a que se refresque ningún token):
--      delete from public.admin_uni where universidad_id = 'uade'
--       and user_id = (select id from auth.users where email = 'PERSONA@uade.edu.ar');
